# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
abstract_target 'CJImageViewDebu' do#多个target，模拟一个抽象的target
# Comment the next line if you don't want to use dynamic frameworks Add this if you are targeting iOS 8+ or using Swift
  use_frameworks!

# Pods for CJImageView
#pod 'CocoaAsyncSocket'
#pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'MJRefresh', '~> 3.1.12'
#pod 'SVProgressHUD', '~> 2.2.5'
pod 'MBProgressHUD', '~> 1.2.0' #Loading框
#pod 'PageMenu', '~> 1.2.8'
pod 'SDWebImage', '~> 3.7.5'
#pod "YBImageBrowser" #图片查看
#pod 'MWPhotoBrowser'
#pod 'YTKNetwork' 基于 AFNetworking 封装的 iOS 网络库
#pod 'FLEX', :configurations => ['Debug']#应用进行样式的修改和控件的读取。
pod 'Masonry','~>0.6.1'
pod 'AFNetworking', '~>3.0'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'YYModel', '~> 1.0.4' #json转model
pod "QBImagePickerController" #图片选择器
#pod 'YYKit'
pod 'YYText'
pod 'YYCache'
pod 'YYCategories'
pod 'YYImage'
pod 'ReactiveObjC'
target 'CJImageViewProduction' do
#target 'CJImageViewTests' do
 #  inherit! :search_paths
  #   pod 'Kiwi'
  pod 'Bugly'
end
#end
target 'CJImageViewDebug' do
  pod 'FBMemoryProfiler'
      #pod 'MLeaksFinder'  #可以把它放在MobileProject_Local的target中 这样就不会影响到产品环境
end
end
